### ISSUE TITLE
The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting.

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-University#9]
When running the command `python3 manage.py runserver`, I get the following message : 
```
$ python3 manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1112599d8>
Traceback (most recent call last):
  File "/Users/Corb3nik/.pyenv/versions/3.6.0/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/Corb3nik/.pyenv/versions/3.6.0/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/Users/Corb3nik/.pyenv/versions/3.6.0/lib/python3.6/site-packages/django/core/management/base.py", line 410, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (staticfiles.E002) The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting.

System check identified 1 issue (0 silenced).
```

**Comment by sergiocampos** [comment]
I only alter  STATIC_ROOT = os.path.join(BASE_DIR, 'static') to **STATIC_ROOT = '/static/'**

**Comment by rezacloner1372** [comment]
You have to enter complete path of static directory:
`STATIC_ROOT = '/home/reza/blog/static/'`

Or If you want to use Collects the static files into **STATIC_ROOT** by `django-admin collectstatic` command you have to use :

`STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')`

**Comment by sousa2323** [comment]
> Eu apenas altero STATIC_ROOT = os.path.join(BASE_DIR, 'static') para **STATIC_ROOT = '/static/'**

I used

**Comment by KaioHerculano** [comment]
Salvou demais
